CommerceApp/Models/Entity/Concrete/Varyants.cs
using CommerceApp.Models.Entity.Abstract;

namespace CommerceApp.Models.Entity.Concrete
{
    public class Varyants : BaseEntity
    {
        public int id { get; set; }
        public int varyantid { get; set; }
        public string varyantname { get; set; }
        public int productid { get; set; }
    }
}

CommerceApp/Controllers/VaryantController.cs
using CommerceApp.DbConnection;
using CommerceApp.Models;
using CommerceApp.Models.Entity.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CommerceApp.Controllers
{
    public class VaryantController : Controller
    {
        DataContext db = new DataContext();
        public IActionResult List()
        {
            var attribute = db.attributes.ToList();
            return View(new AllLayoutModel
            {
                Listattributes = attribute
            });
        }
        [HttpGet]
        public IActionResult VaryantValues(int id)
        {
            var values = db.attributeValues.Where(x => x.categoryAttirbuteid == id).ToList();
            return View(new AllLayoutModel
            {
                ListattributeValues = values
            });
        }

        [HttpGet]
        public IActionResult AddValue(int id)
        {
            return View(new AllLayoutModel());
        }
        [HttpPost]
        public IActionResult AddValue(AllLayoutModel model)
        {

            var id = HttpContext.Request.RouteValues["id"];
            var attributevalue = new AttributeValues
            {
                name = model.attributeValue.name,
                categoryAttirbuteid = Convert.ToInt32(id),
                Attributeid = 0,
                CreateDate = DateTime.Now,
                isActive = true,
                isDelete = false,
                ModifyDate = DateTime.Now
            };
            db.Add(attributevalue);
            db.SaveChanges();
            return Redirect("/Varyant/AddValue/" + id);
        }
        [HttpGet]
        public IActionResult ProductByWithListAttirbute(int id)
        {
            ViewBag.productid = id;
            var listattribute = db.productAttributeValues.Where(x => x.productid == id).ToList();
            return View(new AllLayoutModel
            {
                productAttributeValues = listattribute
            });
        }
        [HttpPost]
        public List<AttributeValueViewModel> GetVariantByProdcutid(string id)
        {
            var listattributeviewmodel = new List<AttributeValueViewModel>();
            var attributesvalu = db.productAttributeValues.Where(x => x.productid == Convert.ToInt32(id)).ToList();
            foreach (var item in attributesvalu)
            {
                var value = db.attributeValues.Where(x => x.id == item.varyantid).FirstOrDefault();
                var attribut = db.attributes.FirstOrDefault(x => x.id == value.categoryAttirbuteid);
                var entity = new AttributeValueViewModel
                {
                    attribute = attribut.name,
                    attributevalue = value.name,
                    renk = item.name,
                    stock=item.stock
                };
                listattributeviewmodel.Add(entity);
            }
            return listattributeviewmodel;
        }
    }
}

CommerceApp/Views/Varyant/AddValue.cshtml
@model AllLayoutModel
@{
    ViewData["Title"] = "AddValue";
    Layout = Model.Layout;
}




<section class="bg0 p-t-23 p-b-140">
    <div class="container">
        <hr />
        <form asp-controller="Varyant" asp-action="AddValue" method="post">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label"> İsim</label>
                        <input id="productName" class="form-control" type="text" asp-for="attributeValue.name" required />
                    </div>
                    <div class="form-group row">
                        <div class="col-md-10 offset-md-2">
                            <button type="submit" id="btn1" class=" center-block btn btn-primary">Ekle</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

CommerceApp/Views/Varyant/List.cshtml
@model AllLayoutModel
@{
    ViewData["Title"] = "List";
    Layout = Model.Layout;
}

<section class="bg0 p-t-23 p-b-140">
    <div class="container">
        <header class="page-header">
            <input type="text" id="txtsearch" placeholder="Müşteri Giriniz" />
        </header>
        <hr />
        <table class="table table-bordered">
            <tr>
                <td>Varyantlar</td>
                <td></td>
            </tr>
            @foreach (var customer in Model.Listattributes)
            {
                <tr class="Search">
                    <td>@customer.name</td>

                    <td style="text-align:right">
                        <a href="/Varyant/VaryantValues/@customer.id" name="id" class="btn-sm btn-success" style="margin-right:6px !important;" title="Fişler">Değerleri</a>
                        <a href="/Varyant/AddValue/@customer.id" name="id" class="btn-sm btn-info" style="margin-right:6px !important;" title="Fişler">Değer Ekle</a>
                        @*   <a href="/Customer/Update/@CommondMethod.ConvertToEncrypt(@customer.id.ToString())" name="id" class="btn-warning btn-sm" style="margin-right:6px !important;" title="Edit">Güncelle</a>
                    <a href="/Check/CheckGive/@CommondMethod.ConvertToEncrypt(@customer.id.ToString())" name="id" class="btn-danger btn-sm" style="margin-right:6px !important;" title="Çek">Çek Ver</a>
                    <a href="/Check/CheckOfCustomer/@CommondMethod.ConvertToEncrypt(@customer.id.ToString())" name="id" class="btn-Secondary btn-sm" style="margin-right:6px !important;" title="Çek">Çekler</a>*@
                    </td>
                </tr>
            }
        </table>
    </div>

</section>

CommerceApp/Views/Varyant/ProductByWithListAttirbute.cshtml
@model AllLayoutModel
@{
    ViewData["Title"] = "ProductByWithListAttirbute";
    Layout = Model.Layout;
}

<head>
    <style>
        #quantity {
            display: none
        }
    </style>
</head>

<section class="bg0 p-t-23 p-b-140">
    <div class="container">
        <hr />
        <input type="text" id="quantity" name="quan" value="@ViewBag.productid" />
        <table id="dtBasicExample3" class="table table-striped table-bordered"
               cellspacing="0" style="text-align:center">
            <thead>
                <tr class="odd" id="tablodoldurss">
                </tr>
            </thead>
            <tbody>
                <tr class="odd" id="tablodoldaltt"></tr>
            </tbody>
        </table>
    </div>
</section>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/gaseltema/vendor/jquery/jquery-3.2.1.min.js"> </script>

<script>
    var productid;
    productid = document.getElementById('quantity').value;
console.log(productid);



    var requestData = { id: productid };

    $(document).ready(function() {
        $('#tablodoldaltt').show();
        $('#tablodoldurss').show();

        $.ajax({
            type: 'POST',
            url: '/Varyant/GetVariantByProdcutid',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: requestData,
            success: function(data) {
                var Adth = '<th>#</th>';
                var inputth = '<th>#</th>';
                debugger;
                for (var i = 0; i < data.length; i++) {
                    Adth += '<th style="min-width:73px;">' + data[i]["name"] + '</th>';
                    var totalvalue = 0;
                    var totalprice = 0;
                    inputth += '<th >';
                    for (var j = 0; j < data[i]["factoryQuantities"].length; j++) {
                        totalprice += data[i]["factoryQuantities"][j]["totalprice"]
                        totalvalue += data[i]["factoryQuantities"][j]["kg"]
                        inputth += '<input style="text-align:center"  value="' + data[i]["factoryQuantities"][j]["kg"] + '"  name="' + data[j] + '_' + j + '" type="text" disabled="disabled"  form-control calcdata" >';
                        console.log([j]["kg"]);
                    }
                    if (data[i]["factoryQuantities"].length > 1) {
                        inputth += '<span>Toplam : </span><input style="text-align:center"  value="' + totalvalue + '"  name="' + data[j] + '_' + j + '" type="text" disabled="disabled"  form-control calcdata" >';
                    }
                    inputth += '</th>';
                    $("#tablodoldurss").html(Adth);
                    $("#tablodoldaltt").html(inputth);
                    document.getElementById('totalprice').value = totalprice;
                }
            }
        });
    });
</script>

CommerceApp/Views/Varyant/VaryantValues.cshtml
@model AllLayoutModel
@{
    ViewData["Title"] = "VaryantValues";
    Layout = Model.Layout;
}


<section class="bg0 p-t-23 p-b-140">
    <div class="container">
        <header class="page-header">
            <input type="text" id="txtsearch" placeholder="varyant Giriniz" />
        </header>
        <hr />
        <table class="table table-bordered">
            <tr>
                <td>Varyantlar</td>
                <td></td>
            </tr>
            @foreach (var customer in Model.ListattributeValues)
            {
                <tr class="Search">
                    <td>@customer.name</td>
                    <td></td>
                </tr>
            }
        </table>
    </div>

</section>