CommerceApp/Controllers/CategoriaAttirbuteController.cs
using CommerceApp.DbConnection;
using Microsoft.AspNetCore.Mvc;

namespace CommerceApp.Controllers
{
    public class CategoriaAttirbuteController : Controller
    {
        DataContext db = new DataContext();
        public IActionResult List()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CategoryAddAttirbute(int categoryid)
        {
            return View();
        }
    }
}

CommerceApp/Views/CategoriaAttirbute/CategoryAddAttirbute.cshtml
@model AllLayoutModel
@{
    ViewData["Title"] = "CategoryAddAttirbute";
    Layout = Model.Layout;
}

<section class="bg0 p-t-23 p-b-140">
    <div class="container">
        <hr />
        <form asp-controller="CategoriaAttirbute" asp-action="CategoryAddAttirbute" method="post">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label"> İsim</label>
                        <input id="productName" class="form-control" type="text" asp-for="attribute.attirbuteid" required />
                    </div>
                    <div class="form-group row">
                        <div class="col-md-10 offset-md-2">
                            <button type="submit" id="btn1" class=" center-block btn btn-primary">Ekle</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>